name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node.js
        uses: actions/setup-node@v1
      - run: npm i
      - run: npm run build --if-present
      - run: npm test
